language: python

# enable caching of installed packages.
cache: pip

# let's test as many versions as we can!
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

install:
- pip install PyYAML pytest bsddb3
- pip install pytest-cov coveralls codecov
- pip install mypy pycodestyle pylint

# the tests + coverage
script:
- make mypy
- make lint
- python -m pytest tests/
- python -m pytest --cov=bakonf --cov-branch tests/

# upload coverage results on success
after_success:
- COVERALLS_PARALLEL=true coveralls
- codecov

notifications:
  webhooks: https://coveralls.io/webhook

# but we do need a system library:
addons:
  apt:
    packages:
      - libdb-dev
