language: python

# let's test as many versions as we can!
python:
    - "2.7"
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"

# we don't need any python dependencies:
install:
- pip install pytest bsddb3
- pip install --install-option "--without-libyaml" PyYaml

# the test command:
script: python -m pytest tests/

# no need for sudo access, silence notice:
sudo: false

# but we do need a system library:
addons:
  apt:
    packages:
      - libdb-dev
