language: python

# enable caching of installed packages.
cache: pip

# let's test as many versions as we can!
python:
    - "2.7"
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"

# we don't need any python dependencies:
install: pip install PyYAML pytest bsddb3

# the test command:
script: python -m pytest tests/

# no need for sudo access, silence notice:
sudo: false

# but we do need a system library:
addons:
  apt:
    packages:
      - libdb-dev
