language: python

# enable caching of installed packages.
cache: pip

# let's test as many versions as we can!
python:
    - "2.7"
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"

install:
- pip install PyYAML pytest bsddb3
- pip install pytest-cov coveralls

# the tests + coverage
script:
- python -m pytest tests/
- python -m pytest --cov=bakonf --cov-branch tests/

# upload coverage results on success
after_success:
- coveralls

# no need for sudo access, silence notice:
sudo: false

# but we do need a system library:
addons:
  apt:
    packages:
      - libdb-dev
